# Managed by Hydra

defaults:
  - base

log:
  WandbLogger:
    project: HAIS
    name: ${experiment_name}
  TensorBoardLogger:
    name: HAIS

trainer:
  max_epochs: 512

optimizer:
    _target_: torch.optim.Adam
    lr: 0.0015

lr_decay:
  decay_start_epoch: 280

network:
  module: HAIS

  m: 32 # 16 or 32
  blocks: [1, 2, 3, 4, 5, 6, 7]
  cluster_blocks: [1, 2]
  block_reps: 2

  use_color: True
  use_normal: False

  fg_thresh: 1
  bg_thresh: 0

  score_scale: 50  # the minimal voxel size is 2cm
  score_fullscale: 20

  prepare_epochs: 100

  point_aggr_radius: 0.03
  cluster_shift_meanActive: 300

  cal_iou_based_on_mask_start_epoch: 200

  use_mask_filter_score_feature_start_epoch: 200
  mask_filter_score_feature_thre: 0.5

  using_set_aggr_in_training: False
  using_set_aggr_in_testing: True

  max_proposal_num: 200


  test:
    TEST_SCORE_THRESH: 0.09
    TEST_NPOINT_THRESH: 100
    test_mask_score_thre: -0.5
