# Managed by Hydra

defaults:
  - base

log:
  WandbLogger:
    project: PointGroup
    name: ${experiment_name}
  TensorBoardLogger:
    name: PointGroup

trainer:
  max_epochs: 496

optimizer:
    _target_: torch.optim.Adam
    lr: 0.002

lr_decay:
  decay_start_epoch: 280

network:
  module: PointGroup

  m: 16 # 16 or 32
  blocks: [1, 2, 3, 4, 5, 6, 7]
  cluster_blocks: [1, 2]
  block_reps: 2

  use_color: True
  use_normal: False

  fg_thresh: 0.75
  bg_thresh: 0.25

  score_scale: 50  # the minimal voxel size is 2cm
  score_fullscale: 14

  prepare_epochs: 128

  cluster:
    # point grouping
    cluster_radius: 0.03
    cluster_meanActive: 50
    cluster_shift_meanActive: 300
    cluster_npoint_thre: 50

  test:
    TEST_NMS_THRESH: 0.3
    TEST_SCORE_THRESH: 0.09
    TEST_NPOINT_THRESH: 100
